name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          # fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{ts,js}
          # only_changed: True
          github_token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}

      - name: Format Prisma
        run: git config --global user.email "actions@github.com" && git config --global user.name "GitHub Action" && npx prisma format && git pull && git commit --amend --no-edit && git push origin -f
